image: node:20

stages:
  - test
  - release

before_script:
  - npm install -g pnpm
  - pnpm install

test:
  stage: test
  script:
    - ls -l
    - cp model/angular.jsonc angular.jsonc
    - ls -l angular.jsonc
    - node index.js
    - node prepare-angular-json.js

publish:
  stage: release
  only:
    - tags
  script:
    - cp model/angular.jsonc angular.jsonc
    - node index.js
    - node prepare-angular-json.js
    # Création du .npmrc temporaire avec le token injecté depuis la variable CI
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
    - pnpm publish --access public --no-git-checks

