image: node:20

stages:
  - test
  - release

before_script:
  - npm install -g pnpm
  - pnpm install

test:
  stage: test
  script:
    - node prepare-angular-json

release:
  stage: release
  only:
    - tags
  script:
    - npm config set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"
    - node prepare-angular-json
    - pnpm publish --access public

