image: node:20

stages:
  - test
  - release

before_script:
  - npm install -g pnpm
  - pnpm install

test:
  stage: test
  script:
    - node index.js
    - node prepare-angular-json.js  # maintenant il existe

release:
  stage: release
  only:
    - tags
  script:
    - npm config set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"
    - cp model/angular.jsonc angular.jsonc
    - node index.js
    - node prepare-angular-json.js
    - pnpm publish --access public

